import os
from git import Repo

repo_url = "https://github.com/Sharieff-Suhaib/dummy_repo.git"
local_dir = "./my_cloned_repo"

if not os.path.exists(local_dir):
    print(f"Cloning into {local_dir}...")
    repo = Repo.clone_from(repo_url, local_dir)
else:
    print(f"Directory {local_dir} already exists. Opening existing repo...")
    repo = Repo(local_dir)

file_name = "example.txt"
file_path = os.path.join(local_dir, file_name)

with open(file_path, "w") as f:
    f.write("This commit was generated by GitPython!\n")
print(f"Created file: {file_name}")

repo.index.add([file_name])
print("Added file to index.")

commit_message = "Automated commit via GitPython"
repo.index.commit(commit_message)
print(f"Committed successfully with message: '{commit_message}'")
